
use super::{Country, Alpha2, Alpha3, Numeric};
pub (super) static COUNTRIES:[Country;249] = [
    // DATA START
    Country {alpha2: Alpha2::AD, alpha3: Alpha3::AND, numeric: Numeric::N020, name: "Andorra", official_name: "the Principality of Andorra"},
    Country {alpha2: Alpha2::AE, alpha3: Alpha3::ARE, numeric: Numeric::N784, name: "United Arab Emirates (the)", official_name: "the United Arab Emirates"},
    Country {alpha2: Alpha2::AF, alpha3: Alpha3::AFG, numeric: Numeric::N004, name: "Afghanistan", official_name: "the Islamic Republic of Afghanistan"},
    Country {alpha2: Alpha2::AG, alpha3: Alpha3::ATG, numeric: Numeric::N028, name: "Antigua and Barbuda", official_name: ""},
    Country {alpha2: Alpha2::AI, alpha3: Alpha3::AIA, numeric: Numeric::N660, name: "Anguilla", official_name: ""},
    Country {alpha2: Alpha2::AL, alpha3: Alpha3::ALB, numeric: Numeric::N008, name: "Albania", official_name: "the Republic of Albania"},
    Country {alpha2: Alpha2::AM, alpha3: Alpha3::ARM, numeric: Numeric::N051, name: "Armenia", official_name: "the Republic of Armenia"},
    Country {alpha2: Alpha2::AO, alpha3: Alpha3::AGO, numeric: Numeric::N024, name: "Angola", official_name: "the Republic of Angola"},
    Country {alpha2: Alpha2::AQ, alpha3: Alpha3::ATA, numeric: Numeric::N010, name: "Antarctica", official_name: ""},
    Country {alpha2: Alpha2::AR, alpha3: Alpha3::ARG, numeric: Numeric::N032, name: "Argentina", official_name: "the Argentine Republic"},
    Country {alpha2: Alpha2::AS, alpha3: Alpha3::ASM, numeric: Numeric::N016, name: "American Samoa", official_name: ""},
    Country {alpha2: Alpha2::AT, alpha3: Alpha3::AUT, numeric: Numeric::N040, name: "Austria", official_name: "the Republic of Austria"},
    Country {alpha2: Alpha2::AU, alpha3: Alpha3::AUS, numeric: Numeric::N036, name: "Australia", official_name: ""},
    Country {alpha2: Alpha2::AW, alpha3: Alpha3::ABW, numeric: Numeric::N533, name: "Aruba", official_name: ""},
    Country {alpha2: Alpha2::AX, alpha3: Alpha3::ALA, numeric: Numeric::N248, name: "Åland Islands", official_name: ""},
    Country {alpha2: Alpha2::AZ, alpha3: Alpha3::AZE, numeric: Numeric::N031, name: "Azerbaijan", official_name: "the Republic of Azerbaijan"},
    Country {alpha2: Alpha2::BA, alpha3: Alpha3::BIH, numeric: Numeric::N070, name: "Bosnia and Herzegovina", official_name: ""},
    Country {alpha2: Alpha2::BB, alpha3: Alpha3::BRB, numeric: Numeric::N052, name: "Barbados", official_name: ""},
    Country {alpha2: Alpha2::BD, alpha3: Alpha3::BGD, numeric: Numeric::N050, name: "Bangladesh", official_name: "the People's Republic of Bangladesh"},
    Country {alpha2: Alpha2::BE, alpha3: Alpha3::BEL, numeric: Numeric::N056, name: "Belgium", official_name: "the Kingdom of Belgium"},
    Country {alpha2: Alpha2::BF, alpha3: Alpha3::BFA, numeric: Numeric::N854, name: "Burkina Faso", official_name: ""},
    Country {alpha2: Alpha2::BG, alpha3: Alpha3::BGR, numeric: Numeric::N100, name: "Bulgaria", official_name: "the Republic of Bulgaria"},
    Country {alpha2: Alpha2::BH, alpha3: Alpha3::BHR, numeric: Numeric::N048, name: "Bahrain", official_name: "the Kingdom of Bahrain"},
    Country {alpha2: Alpha2::BI, alpha3: Alpha3::BDI, numeric: Numeric::N108, name: "Burundi", official_name: "the Republic of Burundi"},
    Country {alpha2: Alpha2::BJ, alpha3: Alpha3::BEN, numeric: Numeric::N204, name: "Benin", official_name: "the Republic of Benin"},
    Country {alpha2: Alpha2::BL, alpha3: Alpha3::BLM, numeric: Numeric::N652, name: "Saint Barthélemy", official_name: ""},
    Country {alpha2: Alpha2::BM, alpha3: Alpha3::BMU, numeric: Numeric::N060, name: "Bermuda", official_name: ""},
    Country {alpha2: Alpha2::BN, alpha3: Alpha3::BRN, numeric: Numeric::N096, name: "Brunei Darussalam", official_name: ""},
    Country {alpha2: Alpha2::BO, alpha3: Alpha3::BOL, numeric: Numeric::N068, name: "Bolivia (Plurinational State of)", official_name: "the Plurinational State of Bolivia"},
    Country {alpha2: Alpha2::BQ, alpha3: Alpha3::BES, numeric: Numeric::N535, name: "Bonaire, Sint Eustatius and Saba", official_name: ""},
    Country {alpha2: Alpha2::BR, alpha3: Alpha3::BRA, numeric: Numeric::N076, name: "Brazil", official_name: "the Federative Republic of Brazil"},
    Country {alpha2: Alpha2::BS, alpha3: Alpha3::BHS, numeric: Numeric::N044, name: "Bahamas (the)", official_name: "the Commonwealth of the Bahamas"},
    Country {alpha2: Alpha2::BT, alpha3: Alpha3::BTN, numeric: Numeric::N064, name: "Bhutan", official_name: "the Kingdom of Bhutan"},
    Country {alpha2: Alpha2::BV, alpha3: Alpha3::BVT, numeric: Numeric::N074, name: "Bouvet Island", official_name: ""},
    Country {alpha2: Alpha2::BW, alpha3: Alpha3::BWA, numeric: Numeric::N072, name: "Botswana", official_name: "the Republic of Botswana"},
    Country {alpha2: Alpha2::BY, alpha3: Alpha3::BLR, numeric: Numeric::N112, name: "Belarus", official_name: "the Republic of Belarus"},
    Country {alpha2: Alpha2::BZ, alpha3: Alpha3::BLZ, numeric: Numeric::N084, name: "Belize", official_name: ""},
    Country {alpha2: Alpha2::CA, alpha3: Alpha3::CAN, numeric: Numeric::N124, name: "Canada", official_name: ""},
    Country {alpha2: Alpha2::CC, alpha3: Alpha3::CCK, numeric: Numeric::N166, name: "Cocos (Keeling) Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::CD, alpha3: Alpha3::COD, numeric: Numeric::N180, name: "Congo (the Democratic Republic of the)", official_name: "the Democratic Republic of the Congo"},
    Country {alpha2: Alpha2::CF, alpha3: Alpha3::CAF, numeric: Numeric::N140, name: "Central African Republic (the)", official_name: "the Central African Republic"},
    Country {alpha2: Alpha2::CG, alpha3: Alpha3::COG, numeric: Numeric::N178, name: "Congo (the)", official_name: "the Republic of the Congo"},
    Country {alpha2: Alpha2::CH, alpha3: Alpha3::CHE, numeric: Numeric::N756, name: "Switzerland", official_name: "the Swiss Confederation"},
    Country {alpha2: Alpha2::CI, alpha3: Alpha3::CIV, numeric: Numeric::N384, name: "Côte d'Ivoire", official_name: "the Republic of Côte d'Ivoire"},
    Country {alpha2: Alpha2::CK, alpha3: Alpha3::COK, numeric: Numeric::N184, name: "Cook Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::CL, alpha3: Alpha3::CHL, numeric: Numeric::N152, name: "Chile", official_name: "the Republic of Chile"},
    Country {alpha2: Alpha2::CM, alpha3: Alpha3::CMR, numeric: Numeric::N120, name: "Cameroon", official_name: "the Republic of Cameroon"},
    Country {alpha2: Alpha2::CN, alpha3: Alpha3::CHN, numeric: Numeric::N156, name: "China", official_name: "the People's Republic of China"},
    Country {alpha2: Alpha2::CO, alpha3: Alpha3::COL, numeric: Numeric::N170, name: "Colombia", official_name: "the Republic of Colombia"},
    Country {alpha2: Alpha2::CR, alpha3: Alpha3::CRI, numeric: Numeric::N188, name: "Costa Rica", official_name: "the Republic of Costa Rica"},
    Country {alpha2: Alpha2::CU, alpha3: Alpha3::CUB, numeric: Numeric::N192, name: "Cuba", official_name: "the Republic of Cuba"},
    Country {alpha2: Alpha2::CV, alpha3: Alpha3::CPV, numeric: Numeric::N132, name: "Cabo Verde", official_name: "the Republic of Cabo Verde"},
    Country {alpha2: Alpha2::CW, alpha3: Alpha3::CUW, numeric: Numeric::N531, name: "Curaçao", official_name: ""},
    Country {alpha2: Alpha2::CX, alpha3: Alpha3::CXR, numeric: Numeric::N162, name: "Christmas Island", official_name: ""},
    Country {alpha2: Alpha2::CY, alpha3: Alpha3::CYP, numeric: Numeric::N196, name: "Cyprus", official_name: "the Republic of Cyprus"},
    Country {alpha2: Alpha2::CZ, alpha3: Alpha3::CZE, numeric: Numeric::N203, name: "Czechia", official_name: "the Czech Republic"},
    Country {alpha2: Alpha2::DE, alpha3: Alpha3::DEU, numeric: Numeric::N276, name: "Germany", official_name: "the Federal Republic of Germany"},
    Country {alpha2: Alpha2::DJ, alpha3: Alpha3::DJI, numeric: Numeric::N262, name: "Djibouti", official_name: "the Republic of Djibouti"},
    Country {alpha2: Alpha2::DK, alpha3: Alpha3::DNK, numeric: Numeric::N208, name: "Denmark", official_name: "the Kingdom of Denmark"},
    Country {alpha2: Alpha2::DM, alpha3: Alpha3::DMA, numeric: Numeric::N212, name: "Dominica", official_name: "the Commonwealth of Dominica"},
    Country {alpha2: Alpha2::DO, alpha3: Alpha3::DOM, numeric: Numeric::N214, name: "Dominican Republic (the)", official_name: "the Dominican Republic"},
    Country {alpha2: Alpha2::DZ, alpha3: Alpha3::DZA, numeric: Numeric::N012, name: "Algeria", official_name: "the People's Democratic Republic of Algeria"},
    Country {alpha2: Alpha2::EC, alpha3: Alpha3::ECU, numeric: Numeric::N218, name: "Ecuador", official_name: "the Republic of Ecuador"},
    Country {alpha2: Alpha2::EE, alpha3: Alpha3::EST, numeric: Numeric::N233, name: "Estonia", official_name: "the Republic of Estonia"},
    Country {alpha2: Alpha2::EG, alpha3: Alpha3::EGY, numeric: Numeric::N818, name: "Egypt", official_name: "the Arab Republic of Egypt"},
    Country {alpha2: Alpha2::EH, alpha3: Alpha3::ESH, numeric: Numeric::N732, name: "Western Sahara*", official_name: ""},
    Country {alpha2: Alpha2::ER, alpha3: Alpha3::ERI, numeric: Numeric::N232, name: "Eritrea", official_name: "the State of Eritrea"},
    Country {alpha2: Alpha2::ES, alpha3: Alpha3::ESP, numeric: Numeric::N724, name: "Spain", official_name: "the Kingdom of Spain"},
    Country {alpha2: Alpha2::ET, alpha3: Alpha3::ETH, numeric: Numeric::N231, name: "Ethiopia", official_name: "the Federal Democratic Republic of Ethiopia"},
    Country {alpha2: Alpha2::FI, alpha3: Alpha3::FIN, numeric: Numeric::N246, name: "Finland", official_name: "the Republic of Finland"},
    Country {alpha2: Alpha2::FJ, alpha3: Alpha3::FJI, numeric: Numeric::N242, name: "Fiji", official_name: "the Republic of Fiji"},
    Country {alpha2: Alpha2::FK, alpha3: Alpha3::FLK, numeric: Numeric::N238, name: "Falkland Islands (the) [Malvinas]", official_name: ""},
    Country {alpha2: Alpha2::FM, alpha3: Alpha3::FSM, numeric: Numeric::N583, name: "Micronesia (Federated States of)", official_name: "the Federated States of Micronesia"},
    Country {alpha2: Alpha2::FO, alpha3: Alpha3::FRO, numeric: Numeric::N234, name: "Faroe Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::FR, alpha3: Alpha3::FRA, numeric: Numeric::N250, name: "France", official_name: "the French Republic"},
    Country {alpha2: Alpha2::GA, alpha3: Alpha3::GAB, numeric: Numeric::N266, name: "Gabon", official_name: "the Gabonese Republic"},
    Country {alpha2: Alpha2::GB, alpha3: Alpha3::GBR, numeric: Numeric::N826, name: "United Kingdom of Great Britain and Northern Ireland (the)", official_name: "the United Kingdom of Great Britain and Northern Ireland"},
    Country {alpha2: Alpha2::GD, alpha3: Alpha3::GRD, numeric: Numeric::N308, name: "Grenada", official_name: ""},
    Country {alpha2: Alpha2::GE, alpha3: Alpha3::GEO, numeric: Numeric::N268, name: "Georgia", official_name: ""},
    Country {alpha2: Alpha2::GF, alpha3: Alpha3::GUF, numeric: Numeric::N254, name: "French Guiana", official_name: ""},
    Country {alpha2: Alpha2::GG, alpha3: Alpha3::GGY, numeric: Numeric::N831, name: "Guernsey", official_name: ""},
    Country {alpha2: Alpha2::GH, alpha3: Alpha3::GHA, numeric: Numeric::N288, name: "Ghana", official_name: "the Republic of Ghana"},
    Country {alpha2: Alpha2::GI, alpha3: Alpha3::GIB, numeric: Numeric::N292, name: "Gibraltar", official_name: ""},
    Country {alpha2: Alpha2::GL, alpha3: Alpha3::GRL, numeric: Numeric::N304, name: "Greenland", official_name: ""},
    Country {alpha2: Alpha2::GM, alpha3: Alpha3::GMB, numeric: Numeric::N270, name: "Gambia (the)", official_name: "the Republic of the Gambia"},
    Country {alpha2: Alpha2::GN, alpha3: Alpha3::GIN, numeric: Numeric::N324, name: "Guinea", official_name: "the Republic of Guinea"},
    Country {alpha2: Alpha2::GP, alpha3: Alpha3::GLP, numeric: Numeric::N312, name: "Guadeloupe", official_name: ""},
    Country {alpha2: Alpha2::GQ, alpha3: Alpha3::GNQ, numeric: Numeric::N226, name: "Equatorial Guinea", official_name: "the Republic of Equatorial Guinea"},
    Country {alpha2: Alpha2::GR, alpha3: Alpha3::GRC, numeric: Numeric::N300, name: "Greece", official_name: "the Hellenic Republic"},
    Country {alpha2: Alpha2::GS, alpha3: Alpha3::SGS, numeric: Numeric::N239, name: "South Georgia and the South Sandwich Islands", official_name: ""},
    Country {alpha2: Alpha2::GT, alpha3: Alpha3::GTM, numeric: Numeric::N320, name: "Guatemala", official_name: "the Republic of Guatemala"},
    Country {alpha2: Alpha2::GU, alpha3: Alpha3::GUM, numeric: Numeric::N316, name: "Guam", official_name: ""},
    Country {alpha2: Alpha2::GW, alpha3: Alpha3::GNB, numeric: Numeric::N624, name: "Guinea-Bissau", official_name: "the Republic of Guinea-Bissau"},
    Country {alpha2: Alpha2::GY, alpha3: Alpha3::GUY, numeric: Numeric::N328, name: "Guyana", official_name: "the Co-operative Republic of Guyana"},
    Country {alpha2: Alpha2::HK, alpha3: Alpha3::HKG, numeric: Numeric::N344, name: "Hong Kong", official_name: "the Hong Kong Special Administrative Region of China"},
    Country {alpha2: Alpha2::HM, alpha3: Alpha3::HMD, numeric: Numeric::N334, name: "Heard Island and McDonald Islands", official_name: ""},
    Country {alpha2: Alpha2::HN, alpha3: Alpha3::HND, numeric: Numeric::N340, name: "Honduras", official_name: "the Republic of Honduras"},
    Country {alpha2: Alpha2::HR, alpha3: Alpha3::HRV, numeric: Numeric::N191, name: "Croatia", official_name: "the Republic of Croatia"},
    Country {alpha2: Alpha2::HT, alpha3: Alpha3::HTI, numeric: Numeric::N332, name: "Haiti", official_name: "the Republic of Haiti"},
    Country {alpha2: Alpha2::HU, alpha3: Alpha3::HUN, numeric: Numeric::N348, name: "Hungary", official_name: ""},
    Country {alpha2: Alpha2::ID, alpha3: Alpha3::IDN, numeric: Numeric::N360, name: "Indonesia", official_name: "the Republic of Indonesia"},
    Country {alpha2: Alpha2::IE, alpha3: Alpha3::IRL, numeric: Numeric::N372, name: "Ireland", official_name: ""},
    Country {alpha2: Alpha2::IL, alpha3: Alpha3::ISR, numeric: Numeric::N376, name: "Israel", official_name: "the State of Israel"},
    Country {alpha2: Alpha2::IM, alpha3: Alpha3::IMN, numeric: Numeric::N833, name: "Isle of Man", official_name: ""},
    Country {alpha2: Alpha2::IN, alpha3: Alpha3::IND, numeric: Numeric::N356, name: "India", official_name: "the Republic of India"},
    Country {alpha2: Alpha2::IO, alpha3: Alpha3::IOT, numeric: Numeric::N086, name: "British Indian Ocean Territory (the)", official_name: ""},
    Country {alpha2: Alpha2::IQ, alpha3: Alpha3::IRQ, numeric: Numeric::N368, name: "Iraq", official_name: "the Republic of Iraq"},
    Country {alpha2: Alpha2::IR, alpha3: Alpha3::IRN, numeric: Numeric::N364, name: "Iran (Islamic Republic of)", official_name: "the Islamic Republic of Iran"},
    Country {alpha2: Alpha2::IS, alpha3: Alpha3::ISL, numeric: Numeric::N352, name: "Iceland", official_name: "the Republic of Iceland"},
    Country {alpha2: Alpha2::IT, alpha3: Alpha3::ITA, numeric: Numeric::N380, name: "Italy", official_name: "the Republic of Italy"},
    Country {alpha2: Alpha2::JE, alpha3: Alpha3::JEY, numeric: Numeric::N832, name: "Jersey", official_name: ""},
    Country {alpha2: Alpha2::JM, alpha3: Alpha3::JAM, numeric: Numeric::N388, name: "Jamaica", official_name: ""},
    Country {alpha2: Alpha2::JO, alpha3: Alpha3::JOR, numeric: Numeric::N400, name: "Jordan", official_name: "the Hashemite Kingdom of Jordan"},
    Country {alpha2: Alpha2::JP, alpha3: Alpha3::JPN, numeric: Numeric::N392, name: "Japan", official_name: ""},
    Country {alpha2: Alpha2::KE, alpha3: Alpha3::KEN, numeric: Numeric::N404, name: "Kenya", official_name: "the Republic of Kenya"},
    Country {alpha2: Alpha2::KG, alpha3: Alpha3::KGZ, numeric: Numeric::N417, name: "Kyrgyzstan", official_name: "the Kyrgyz Republic"},
    Country {alpha2: Alpha2::KH, alpha3: Alpha3::KHM, numeric: Numeric::N116, name: "Cambodia", official_name: "the Kingdom of Cambodia"},
    Country {alpha2: Alpha2::KI, alpha3: Alpha3::KIR, numeric: Numeric::N296, name: "Kiribati", official_name: "the Republic of Kiribati"},
    Country {alpha2: Alpha2::KM, alpha3: Alpha3::COM, numeric: Numeric::N174, name: "Comoros (the)", official_name: "the Union of the Comoros"},
    Country {alpha2: Alpha2::KN, alpha3: Alpha3::KNA, numeric: Numeric::N659, name: "Saint Kitts and Nevis", official_name: ""},
    Country {alpha2: Alpha2::KP, alpha3: Alpha3::PRK, numeric: Numeric::N408, name: "Korea (the Democratic People's Republic of)", official_name: "the Democratic People's Republic of Korea"},
    Country {alpha2: Alpha2::KR, alpha3: Alpha3::KOR, numeric: Numeric::N410, name: "Korea (the Republic of)", official_name: "the Republic of Korea"},
    Country {alpha2: Alpha2::KW, alpha3: Alpha3::KWT, numeric: Numeric::N414, name: "Kuwait", official_name: "the State of Kuwait"},
    Country {alpha2: Alpha2::KY, alpha3: Alpha3::CYM, numeric: Numeric::N136, name: "Cayman Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::KZ, alpha3: Alpha3::KAZ, numeric: Numeric::N398, name: "Kazakhstan", official_name: "the Republic of Kazakhstan"},
    Country {alpha2: Alpha2::LA, alpha3: Alpha3::LAO, numeric: Numeric::N418, name: "Lao People's Democratic Republic (the)", official_name: "the Lao People's Democratic Republic"},
    Country {alpha2: Alpha2::LB, alpha3: Alpha3::LBN, numeric: Numeric::N422, name: "Lebanon", official_name: "the Lebanese Republic"},
    Country {alpha2: Alpha2::LC, alpha3: Alpha3::LCA, numeric: Numeric::N662, name: "Saint Lucia", official_name: ""},
    Country {alpha2: Alpha2::LI, alpha3: Alpha3::LIE, numeric: Numeric::N438, name: "Liechtenstein", official_name: "the Principality of Liechtenstein"},
    Country {alpha2: Alpha2::LK, alpha3: Alpha3::LKA, numeric: Numeric::N144, name: "Sri Lanka", official_name: "the Democratic Socialist Republic of Sri Lanka"},
    Country {alpha2: Alpha2::LR, alpha3: Alpha3::LBR, numeric: Numeric::N430, name: "Liberia", official_name: "the Republic of Liberia"},
    Country {alpha2: Alpha2::LS, alpha3: Alpha3::LSO, numeric: Numeric::N426, name: "Lesotho", official_name: "the Kingdom of Lesotho"},
    Country {alpha2: Alpha2::LT, alpha3: Alpha3::LTU, numeric: Numeric::N440, name: "Lithuania", official_name: "the Republic of Lithuania"},
    Country {alpha2: Alpha2::LU, alpha3: Alpha3::LUX, numeric: Numeric::N442, name: "Luxembourg", official_name: "the Grand Duchy of Luxembourg"},
    Country {alpha2: Alpha2::LV, alpha3: Alpha3::LVA, numeric: Numeric::N428, name: "Latvia", official_name: "the Republic of Latvia"},
    Country {alpha2: Alpha2::LY, alpha3: Alpha3::LBY, numeric: Numeric::N434, name: "Libya", official_name: "the State of Libya"},
    Country {alpha2: Alpha2::MA, alpha3: Alpha3::MAR, numeric: Numeric::N504, name: "Morocco", official_name: "the Kingdom of Morocco"},
    Country {alpha2: Alpha2::MC, alpha3: Alpha3::MCO, numeric: Numeric::N492, name: "Monaco", official_name: "the Principality of Monaco"},
    Country {alpha2: Alpha2::MD, alpha3: Alpha3::MDA, numeric: Numeric::N498, name: "Moldova (the Republic of)", official_name: "the Republic of Moldova"},
    Country {alpha2: Alpha2::ME, alpha3: Alpha3::MNE, numeric: Numeric::N499, name: "Montenegro", official_name: ""},
    Country {alpha2: Alpha2::MF, alpha3: Alpha3::MAF, numeric: Numeric::N663, name: "Saint Martin (French part)", official_name: ""},
    Country {alpha2: Alpha2::MG, alpha3: Alpha3::MDG, numeric: Numeric::N450, name: "Madagascar", official_name: "the Republic of Madagascar"},
    Country {alpha2: Alpha2::MH, alpha3: Alpha3::MHL, numeric: Numeric::N584, name: "Marshall Islands (the)", official_name: "the Republic of the Marshall Islands"},
    Country {alpha2: Alpha2::MK, alpha3: Alpha3::MKD, numeric: Numeric::N807, name: "North Macedonia", official_name: "the Republic of North Macedonia"},
    Country {alpha2: Alpha2::ML, alpha3: Alpha3::MLI, numeric: Numeric::N466, name: "Mali", official_name: "the Republic of Mali"},
    Country {alpha2: Alpha2::MM, alpha3: Alpha3::MMR, numeric: Numeric::N104, name: "Myanmar", official_name: "the Republic of the Union of Myanmar"},
    Country {alpha2: Alpha2::MN, alpha3: Alpha3::MNG, numeric: Numeric::N496, name: "Mongolia", official_name: ""},
    Country {alpha2: Alpha2::MO, alpha3: Alpha3::MAC, numeric: Numeric::N446, name: "Macao", official_name: "Macao Special Administrative Region of China"},
    Country {alpha2: Alpha2::MP, alpha3: Alpha3::MNP, numeric: Numeric::N580, name: "Northern Mariana Islands (the)", official_name: "the Commonwealth of the Northern Mariana Islands"},
    Country {alpha2: Alpha2::MQ, alpha3: Alpha3::MTQ, numeric: Numeric::N474, name: "Martinique", official_name: ""},
    Country {alpha2: Alpha2::MR, alpha3: Alpha3::MRT, numeric: Numeric::N478, name: "Mauritania", official_name: "the Islamic Republic of Mauritania"},
    Country {alpha2: Alpha2::MS, alpha3: Alpha3::MSR, numeric: Numeric::N500, name: "Montserrat", official_name: ""},
    Country {alpha2: Alpha2::MT, alpha3: Alpha3::MLT, numeric: Numeric::N470, name: "Malta", official_name: "the Republic of Malta"},
    Country {alpha2: Alpha2::MU, alpha3: Alpha3::MUS, numeric: Numeric::N480, name: "Mauritius", official_name: "the Republic of Mauritius"},
    Country {alpha2: Alpha2::MV, alpha3: Alpha3::MDV, numeric: Numeric::N462, name: "Maldives", official_name: "the Republic of Maldives"},
    Country {alpha2: Alpha2::MW, alpha3: Alpha3::MWI, numeric: Numeric::N454, name: "Malawi", official_name: "the Republic of Malawi"},
    Country {alpha2: Alpha2::MX, alpha3: Alpha3::MEX, numeric: Numeric::N484, name: "Mexico", official_name: "the United Mexican States"},
    Country {alpha2: Alpha2::MY, alpha3: Alpha3::MYS, numeric: Numeric::N458, name: "Malaysia", official_name: ""},
    Country {alpha2: Alpha2::MZ, alpha3: Alpha3::MOZ, numeric: Numeric::N508, name: "Mozambique", official_name: "the Republic of Mozambique"},
    Country {alpha2: Alpha2::NA, alpha3: Alpha3::NAM, numeric: Numeric::N516, name: "Namibia", official_name: "the Republic of Namibia"},
    Country {alpha2: Alpha2::NC, alpha3: Alpha3::NCL, numeric: Numeric::N540, name: "New Caledonia", official_name: ""},
    Country {alpha2: Alpha2::NE, alpha3: Alpha3::NER, numeric: Numeric::N562, name: "Niger (the)", official_name: "the Republic of the Niger"},
    Country {alpha2: Alpha2::NF, alpha3: Alpha3::NFK, numeric: Numeric::N574, name: "Norfolk Island", official_name: ""},
    Country {alpha2: Alpha2::NG, alpha3: Alpha3::NGA, numeric: Numeric::N566, name: "Nigeria", official_name: "the Federal Republic of Nigeria"},
    Country {alpha2: Alpha2::NI, alpha3: Alpha3::NIC, numeric: Numeric::N558, name: "Nicaragua", official_name: "the Republic of Nicaragua"},
    Country {alpha2: Alpha2::NL, alpha3: Alpha3::NLD, numeric: Numeric::N528, name: "Netherlands (the)", official_name: "the Kingdom of the Netherlands"},
    Country {alpha2: Alpha2::NO, alpha3: Alpha3::NOR, numeric: Numeric::N578, name: "Norway", official_name: "the Kingdom of Norway"},
    Country {alpha2: Alpha2::NP, alpha3: Alpha3::NPL, numeric: Numeric::N524, name: "Nepal", official_name: ""},
    Country {alpha2: Alpha2::NR, alpha3: Alpha3::NRU, numeric: Numeric::N520, name: "Nauru", official_name: "the Republic of Nauru"},
    Country {alpha2: Alpha2::NU, alpha3: Alpha3::NIU, numeric: Numeric::N570, name: "Niue", official_name: ""},
    Country {alpha2: Alpha2::NZ, alpha3: Alpha3::NZL, numeric: Numeric::N554, name: "New Zealand", official_name: ""},
    Country {alpha2: Alpha2::OM, alpha3: Alpha3::OMN, numeric: Numeric::N512, name: "Oman", official_name: "the Sultanate of Oman"},
    Country {alpha2: Alpha2::PA, alpha3: Alpha3::PAN, numeric: Numeric::N591, name: "Panama", official_name: "the Republic of Panama"},
    Country {alpha2: Alpha2::PE, alpha3: Alpha3::PER, numeric: Numeric::N604, name: "Peru", official_name: "the Republic of Peru"},
    Country {alpha2: Alpha2::PF, alpha3: Alpha3::PYF, numeric: Numeric::N258, name: "French Polynesia", official_name: ""},
    Country {alpha2: Alpha2::PG, alpha3: Alpha3::PNG, numeric: Numeric::N598, name: "Papua New Guinea", official_name: "the Independent State of Papua New Guinea"},
    Country {alpha2: Alpha2::PH, alpha3: Alpha3::PHL, numeric: Numeric::N608, name: "Philippines (the)", official_name: "the Republic of the Philippines"},
    Country {alpha2: Alpha2::PK, alpha3: Alpha3::PAK, numeric: Numeric::N586, name: "Pakistan", official_name: "the Islamic Republic of Pakistan"},
    Country {alpha2: Alpha2::PL, alpha3: Alpha3::POL, numeric: Numeric::N616, name: "Poland", official_name: "the Republic of Poland"},
    Country {alpha2: Alpha2::PM, alpha3: Alpha3::SPM, numeric: Numeric::N666, name: "Saint Pierre and Miquelon", official_name: ""},
    Country {alpha2: Alpha2::PN, alpha3: Alpha3::PCN, numeric: Numeric::N612, name: "Pitcairn", official_name: ""},
    Country {alpha2: Alpha2::PR, alpha3: Alpha3::PRI, numeric: Numeric::N630, name: "Puerto Rico", official_name: ""},
    Country {alpha2: Alpha2::PS, alpha3: Alpha3::PSE, numeric: Numeric::N275, name: "Palestine, State of", official_name: "the State of Palestine"},
    Country {alpha2: Alpha2::PT, alpha3: Alpha3::PRT, numeric: Numeric::N620, name: "Portugal", official_name: "the Portuguese Republic"},
    Country {alpha2: Alpha2::PW, alpha3: Alpha3::PLW, numeric: Numeric::N585, name: "Palau", official_name: "the Republic of Palau"},
    Country {alpha2: Alpha2::PY, alpha3: Alpha3::PRY, numeric: Numeric::N600, name: "Paraguay", official_name: "the Republic of Paraguay"},
    Country {alpha2: Alpha2::QA, alpha3: Alpha3::QAT, numeric: Numeric::N634, name: "Qatar", official_name: "the State of Qatar"},
    Country {alpha2: Alpha2::RE, alpha3: Alpha3::REU, numeric: Numeric::N638, name: "Réunion", official_name: ""},
    Country {alpha2: Alpha2::RO, alpha3: Alpha3::ROU, numeric: Numeric::N642, name: "Romania", official_name: ""},
    Country {alpha2: Alpha2::RS, alpha3: Alpha3::SRB, numeric: Numeric::N688, name: "Serbia", official_name: "the Republic of Serbia"},
    Country {alpha2: Alpha2::RU, alpha3: Alpha3::RUS, numeric: Numeric::N643, name: "Russian Federation (the)", official_name: "the Russian Federation"},
    Country {alpha2: Alpha2::RW, alpha3: Alpha3::RWA, numeric: Numeric::N646, name: "Rwanda", official_name: "the Republic of Rwanda"},
    Country {alpha2: Alpha2::SA, alpha3: Alpha3::SAU, numeric: Numeric::N682, name: "Saudi Arabia", official_name: "the Kingdom of Saudi Arabia"},
    Country {alpha2: Alpha2::SB, alpha3: Alpha3::SLB, numeric: Numeric::N090, name: "Solomon Islands", official_name: ""},
    Country {alpha2: Alpha2::SC, alpha3: Alpha3::SYC, numeric: Numeric::N690, name: "Seychelles", official_name: "the Republic of Seychelles"},
    Country {alpha2: Alpha2::SD, alpha3: Alpha3::SDN, numeric: Numeric::N729, name: "Sudan (the)", official_name: "the Republic of the Sudan"},
    Country {alpha2: Alpha2::SE, alpha3: Alpha3::SWE, numeric: Numeric::N752, name: "Sweden", official_name: "the Kingdom of Sweden"},
    Country {alpha2: Alpha2::SG, alpha3: Alpha3::SGP, numeric: Numeric::N702, name: "Singapore", official_name: "the Republic of Singapore"},
    Country {alpha2: Alpha2::SH, alpha3: Alpha3::SHN, numeric: Numeric::N654, name: "Saint Helena, Ascension and Tristan da Cunha", official_name: ""},
    Country {alpha2: Alpha2::SI, alpha3: Alpha3::SVN, numeric: Numeric::N705, name: "Slovenia", official_name: "the Republic of Slovenia"},
    Country {alpha2: Alpha2::SJ, alpha3: Alpha3::SJM, numeric: Numeric::N744, name: "Svalbard and Jan Mayen", official_name: ""},
    Country {alpha2: Alpha2::SK, alpha3: Alpha3::SVK, numeric: Numeric::N703, name: "Slovakia", official_name: "the Slovak Republic"},
    Country {alpha2: Alpha2::SL, alpha3: Alpha3::SLE, numeric: Numeric::N694, name: "Sierra Leone", official_name: "the Republic of Sierra Leone"},
    Country {alpha2: Alpha2::SM, alpha3: Alpha3::SMR, numeric: Numeric::N674, name: "San Marino", official_name: "the Republic of San Marino"},
    Country {alpha2: Alpha2::SN, alpha3: Alpha3::SEN, numeric: Numeric::N686, name: "Senegal", official_name: "the Republic of Senegal"},
    Country {alpha2: Alpha2::SO, alpha3: Alpha3::SOM, numeric: Numeric::N706, name: "Somalia", official_name: "the Federal Republic of Somalia"},
    Country {alpha2: Alpha2::SR, alpha3: Alpha3::SUR, numeric: Numeric::N740, name: "Suriname", official_name: "the Republic of Suriname"},
    Country {alpha2: Alpha2::SS, alpha3: Alpha3::SSD, numeric: Numeric::N728, name: "South Sudan", official_name: "the Republic of South Sudan"},
    Country {alpha2: Alpha2::ST, alpha3: Alpha3::STP, numeric: Numeric::N678, name: "Sao Tome and Principe", official_name: "the Democratic Republic of Sao Tome and Principe"},
    Country {alpha2: Alpha2::SV, alpha3: Alpha3::SLV, numeric: Numeric::N222, name: "El Salvador", official_name: "the Republic of El Salvador"},
    Country {alpha2: Alpha2::SX, alpha3: Alpha3::SXM, numeric: Numeric::N534, name: "Sint Maarten (Dutch part)", official_name: ""},
    Country {alpha2: Alpha2::SY, alpha3: Alpha3::SYR, numeric: Numeric::N760, name: "Syrian Arab Republic (the)", official_name: "the Syrian Arab Republic"},
    Country {alpha2: Alpha2::SZ, alpha3: Alpha3::SWZ, numeric: Numeric::N748, name: "Eswatini", official_name: "the Kingdom of Eswatini"},
    Country {alpha2: Alpha2::TC, alpha3: Alpha3::TCA, numeric: Numeric::N796, name: "Turks and Caicos Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::TD, alpha3: Alpha3::TCD, numeric: Numeric::N148, name: "Chad", official_name: "the Republic of Chad"},
    Country {alpha2: Alpha2::TF, alpha3: Alpha3::ATF, numeric: Numeric::N260, name: "French Southern Territories (the)", official_name: ""},
    Country {alpha2: Alpha2::TG, alpha3: Alpha3::TGO, numeric: Numeric::N768, name: "Togo", official_name: "the Togolese Republic"},
    Country {alpha2: Alpha2::TH, alpha3: Alpha3::THA, numeric: Numeric::N764, name: "Thailand", official_name: "the Kingdom of Thailand"},
    Country {alpha2: Alpha2::TJ, alpha3: Alpha3::TJK, numeric: Numeric::N762, name: "Tajikistan", official_name: "the Republic of Tajikistan"},
    Country {alpha2: Alpha2::TK, alpha3: Alpha3::TKL, numeric: Numeric::N772, name: "Tokelau", official_name: ""},
    Country {alpha2: Alpha2::TL, alpha3: Alpha3::TLS, numeric: Numeric::N626, name: "Timor-Leste", official_name: "the Democratic Republic of Timor-Leste"},
    Country {alpha2: Alpha2::TM, alpha3: Alpha3::TKM, numeric: Numeric::N795, name: "Turkmenistan", official_name: ""},
    Country {alpha2: Alpha2::TN, alpha3: Alpha3::TUN, numeric: Numeric::N788, name: "Tunisia", official_name: "the Republic of Tunisia"},
    Country {alpha2: Alpha2::TO, alpha3: Alpha3::TON, numeric: Numeric::N776, name: "Tonga", official_name: "the Kingdom of Tonga"},
    Country {alpha2: Alpha2::TR, alpha3: Alpha3::TUR, numeric: Numeric::N792, name: "Turkey", official_name: "the Republic of Turkey"},
    Country {alpha2: Alpha2::TT, alpha3: Alpha3::TTO, numeric: Numeric::N780, name: "Trinidad and Tobago", official_name: "the Republic of Trinidad and Tobago"},
    Country {alpha2: Alpha2::TV, alpha3: Alpha3::TUV, numeric: Numeric::N798, name: "Tuvalu", official_name: ""},
    Country {alpha2: Alpha2::TW, alpha3: Alpha3::TWN, numeric: Numeric::N158, name: "Taiwan (Province of China)", official_name: ""},
    Country {alpha2: Alpha2::TZ, alpha3: Alpha3::TZA, numeric: Numeric::N834, name: "Tanzania, the United Republic of", official_name: "the United Republic of Tanzania"},
    Country {alpha2: Alpha2::UA, alpha3: Alpha3::UKR, numeric: Numeric::N804, name: "Ukraine", official_name: ""},
    Country {alpha2: Alpha2::UG, alpha3: Alpha3::UGA, numeric: Numeric::N800, name: "Uganda", official_name: "the Republic of Uganda"},
    Country {alpha2: Alpha2::UM, alpha3: Alpha3::UMI, numeric: Numeric::N581, name: "United States Minor Outlying Islands (the)", official_name: ""},
    Country {alpha2: Alpha2::US, alpha3: Alpha3::USA, numeric: Numeric::N840, name: "United States of America (the)", official_name: "the United States of America"},
    Country {alpha2: Alpha2::UY, alpha3: Alpha3::URY, numeric: Numeric::N858, name: "Uruguay", official_name: "the Eastern Republic of Uruguay"},
    Country {alpha2: Alpha2::UZ, alpha3: Alpha3::UZB, numeric: Numeric::N860, name: "Uzbekistan", official_name: "the Republic of Uzbekistan"},
    Country {alpha2: Alpha2::VA, alpha3: Alpha3::VAT, numeric: Numeric::N336, name: "Holy See (the)", official_name: ""},
    Country {alpha2: Alpha2::VC, alpha3: Alpha3::VCT, numeric: Numeric::N670, name: "Saint Vincent and the Grenadines", official_name: ""},
    Country {alpha2: Alpha2::VE, alpha3: Alpha3::VEN, numeric: Numeric::N862, name: "Venezuela (Bolivarian Republic of)", official_name: "the Bolivarian Republic of Venezuela"},
    Country {alpha2: Alpha2::VG, alpha3: Alpha3::VGB, numeric: Numeric::N092, name: "Virgin Islands (British)", official_name: "British Virgin Islands (the)"},
    Country {alpha2: Alpha2::VI, alpha3: Alpha3::VIR, numeric: Numeric::N850, name: "Virgin Islands (U.S.)", official_name: "the Virgin Islands of the United States"},
    Country {alpha2: Alpha2::VN, alpha3: Alpha3::VNM, numeric: Numeric::N704, name: "Viet Nam", official_name: "the Socialist Republic of Viet Nam"},
    Country {alpha2: Alpha2::VU, alpha3: Alpha3::VUT, numeric: Numeric::N548, name: "Vanuatu", official_name: "the Republic of Vanuatu"},
    Country {alpha2: Alpha2::WF, alpha3: Alpha3::WLF, numeric: Numeric::N876, name: "Wallis and Futuna", official_name: "Wallis and Futuna Islands"},
    Country {alpha2: Alpha2::WS, alpha3: Alpha3::WSM, numeric: Numeric::N882, name: "Samoa", official_name: "the Independent State of Samoa"},
    Country {alpha2: Alpha2::YE, alpha3: Alpha3::YEM, numeric: Numeric::N887, name: "Yemen", official_name: "the Republic of Yemen"},
    Country {alpha2: Alpha2::YT, alpha3: Alpha3::MYT, numeric: Numeric::N175, name: "Mayotte", official_name: ""},
    Country {alpha2: Alpha2::ZA, alpha3: Alpha3::ZAF, numeric: Numeric::N710, name: "South Africa", official_name: "the Republic of South Africa"},
    Country {alpha2: Alpha2::ZM, alpha3: Alpha3::ZMB, numeric: Numeric::N894, name: "Zambia", official_name: "the Republic of Zambia"},
    Country {alpha2: Alpha2::ZW, alpha3: Alpha3::ZWE, numeric: Numeric::N716, name: "Zimbabwe", official_name: "the Republic of Zimbabwe"},
    // DATA END
];
