
use super::{Currency, Code, Numeric};
pub (super) static CURRENCIES:[Currency;180] = [
    // DATA START
    Currency { code: Code::BSD, numeric: Numeric::N044, name: "Bahamian Dollar", units: 2, symbol: "$", countries: "BS" },
    Currency { code: Code::BTN, numeric: Numeric::N064, name: "Ngultrum", units: 2, symbol: "", countries: "BT" },
    Currency { code: Code::NIO, numeric: Numeric::N558, name: "Cordoba Oro", units: 2, symbol: "C$", countries: "NI" },
    Currency { code: Code::XSU, numeric: Numeric::N994, name: "Sucre", units: 0, symbol: "", countries: "" },
    Currency { code: Code::KHR, numeric: Numeric::N116, name: "Riel", units: 2, symbol: "៛", countries: "KH" },
    Currency { code: Code::CLP, numeric: Numeric::N152, name: "Chilean Peso", units: 0, symbol: "$", countries: "CL" },
    Currency { code: Code::BND, numeric: Numeric::N096, name: "Brunei Dollar", units: 2, symbol: "$", countries: "BN" },
    Currency { code: Code::BOB, numeric: Numeric::N068, name: "Boliviano", units: 2, symbol: "$b", countries: "BO" },
    Currency { code: Code::VUV, numeric: Numeric::N548, name: "Vatu", units: 0, symbol: "", countries: "VU" },
    Currency { code: Code::PEN, numeric: Numeric::N604, name: "Sol", units: 2, symbol: "S/.", countries: "PE" },
    Currency { code: Code::XAU, numeric: Numeric::N959, name: "Gold", units: 0, symbol: "", countries: "" },
    Currency { code: Code::LAK, numeric: Numeric::N418, name: "Lao Kip", units: 2, symbol: "₭", countries: "" },
    Currency { code: Code::BRL, numeric: Numeric::N986, name: "Brazilian Real", units: 2, symbol: "R$", countries: "BR" },
    Currency { code: Code::CDF, numeric: Numeric::N976, name: "Congolese Franc", units: 2, symbol: "", countries: "CD" },
    Currency { code: Code::NZD, numeric: Numeric::N554, name: "New Zealand Dollar", units: 2, symbol: "$", countries: "CK,NZ,NU,PN,TK" },
    Currency { code: Code::SCR, numeric: Numeric::N690, name: "Seychelles Rupee", units: 2, symbol: "₨", countries: "SC" },
    Currency { code: Code::TMT, numeric: Numeric::N934, name: "Turkmenistan New Manat", units: 2, symbol: "", countries: "TM" },
    Currency { code: Code::BGN, numeric: Numeric::N975, name: "Bulgarian Lev", units: 2, symbol: "лв", countries: "BG" },
    Currency { code: Code::CAD, numeric: Numeric::N124, name: "Canadian Dollar", units: 2, symbol: "$", countries: "CA" },
    Currency { code: Code::GMD, numeric: Numeric::N270, name: "Dalasi", units: 2, symbol: "", countries: "GM" },
    Currency { code: Code::TRY, numeric: Numeric::N949, name: "Turkish Lira", units: 2, symbol: "", countries: "TR" },
    Currency { code: Code::AUD, numeric: Numeric::N036, name: "Australian Dollar", units: 2, symbol: "$", countries: "AU,CX,CC,HM,KI,NR,NF,TV" },
    Currency { code: Code::ERN, numeric: Numeric::N232, name: "Nakfa", units: 2, symbol: "", countries: "ER" },
    Currency { code: Code::EUR, numeric: Numeric::N978, name: "Euro", units: 2, symbol: "€", countries: "AX,AD,AT,BE,CY,EE,FI,FR,GF,TF,DE,GR,GP,VA,IE,IT,LV,LT,LU,MT,MQ,YT,MC,ME,NL,PT,MF,PM,SM,SK,SI,ES" },
    Currency { code: Code::BYN, numeric: Numeric::N933, name: "Belarusian Ruble", units: 2, symbol: "Br", countries: "BY" },
    Currency { code: Code::UZS, numeric: Numeric::N860, name: "Uzbekistan Sum", units: 2, symbol: "лв", countries: "UZ" },
    Currency { code: Code::XBA, numeric: Numeric::N955, name: "Bond Markets Unit European Composite Unit (EURCO)", units: 0, symbol: "", countries: "" },
    Currency { code: Code::AMD, numeric: Numeric::N051, name: "Armenian Dram", units: 2, symbol: "", countries: "AM" },
    Currency { code: Code::ZAR, numeric: Numeric::N710, name: "Rand", units: 2, symbol: "R", countries: "LS,NA,ZA" },
    Currency { code: Code::BMD, numeric: Numeric::N060, name: "Bermudian Dollar", units: 2, symbol: "$", countries: "BM" },
    Currency { code: Code::AWG, numeric: Numeric::N533, name: "Aruban Florin", units: 2, symbol: "ƒ", countries: "AW" },
    Currency { code: Code::MMK, numeric: Numeric::N104, name: "Kyat", units: 2, symbol: "", countries: "MM" },
    Currency { code: Code::XAF, numeric: Numeric::N950, name: "CFA Franc BEAC", units: 0, symbol: "", countries: "CM,CF,TD,CG,GQ,GA" },
    Currency { code: Code::CRC, numeric: Numeric::N188, name: "Costa Rican Colon", units: 2, symbol: "₡", countries: "CR" },
    Currency { code: Code::CUC, numeric: Numeric::N931, name: "Peso Convertible", units: 2, symbol: "", countries: "CU" },
    Currency { code: Code::ARS, numeric: Numeric::N032, name: "Argentine Peso", units: 2, symbol: "$", countries: "AR" },
    Currency { code: Code::MKD, numeric: Numeric::N807, name: "Denar", units: 2, symbol: "ден", countries: "MK" },
    Currency { code: Code::DKK, numeric: Numeric::N208, name: "Danish Krone", units: 2, symbol: "kr", countries: "DK,FO,GL" },
    Currency { code: Code::MXV, numeric: Numeric::N979, name: "Mexican Unidad de Inversion (UDI)", units: 2, symbol: "", countries: "MX" },
    Currency { code: Code::MDL, numeric: Numeric::N498, name: "Moldovan Leu", units: 2, symbol: "", countries: "MD" },
    Currency { code: Code::LKR, numeric: Numeric::N144, name: "Sri Lanka Rupee", units: 2, symbol: "₨", countries: "LK" },
    Currency { code: Code::IRR, numeric: Numeric::N364, name: "Iranian Rial", units: 2, symbol: "﷼", countries: "IR" },
    Currency { code: Code::TZS, numeric: Numeric::N834, name: "Tanzanian Shilling", units: 2, symbol: "", countries: "" },
    Currency { code: Code::ZWL, numeric: Numeric::N932, name: "Zimbabwe Dollar", units: 2, symbol: "", countries: "ZW" },
    Currency { code: Code::KYD, numeric: Numeric::N136, name: "Cayman Islands Dollar", units: 2, symbol: "$", countries: "KY" },
    Currency { code: Code::FJD, numeric: Numeric::N242, name: "Fiji Dollar", units: 2, symbol: "$", countries: "FJ" },
    Currency { code: Code::USD, numeric: Numeric::N840, name: "US Dollar", units: 2, symbol: "$", countries: "AS,BQ,IO,EC,SV,GU,HT,MH,FM,MP,PW,PA,PR,TL,TC,UM,US,VG,VI" },
    Currency { code: Code::MAD, numeric: Numeric::N504, name: "Moroccan Dirham", units: 2, symbol: "", countries: "MA" },
    Currency { code: Code::NAD, numeric: Numeric::N516, name: "Namibia Dollar", units: 2, symbol: "$", countries: "NA" },
    Currency { code: Code::IDR, numeric: Numeric::N360, name: "Rupiah", units: 2, symbol: "Rp", countries: "ID" },
    Currency { code: Code::CNY, numeric: Numeric::N156, name: "Yuan Renminbi", units: 2, symbol: "¥", countries: "CN" },
    Currency { code: Code::GEL, numeric: Numeric::N981, name: "Lari", units: 2, symbol: "", countries: "GE" },
    Currency { code: Code::PGK, numeric: Numeric::N598, name: "Kina", units: 2, symbol: "", countries: "PG" },
    Currency { code: Code::GNF, numeric: Numeric::N324, name: "Guinean Franc", units: 0, symbol: "", countries: "GN" },
    Currency { code: Code::CHW, numeric: Numeric::N948, name: "WIR Franc", units: 2, symbol: "", countries: "CH" },
    Currency { code: Code::XPD, numeric: Numeric::N964, name: "Palladium", units: 0, symbol: "", countries: "" },
    Currency { code: Code::TOP, numeric: Numeric::N776, name: "Pa’anga", units: 2, symbol: "", countries: "TO" },
    Currency { code: Code::STN, numeric: Numeric::N930, name: "Dobra", units: 2, symbol: "", countries: "ST" },
    Currency { code: Code::JOD, numeric: Numeric::N400, name: "Jordanian Dinar", units: 3, symbol: "", countries: "JO" },
    Currency { code: Code::MVR, numeric: Numeric::N462, name: "Rufiyaa", units: 2, symbol: "", countries: "MV" },
    Currency { code: Code::BHD, numeric: Numeric::N048, name: "Bahraini Dinar", units: 3, symbol: "", countries: "BH" },
    Currency { code: Code::HUF, numeric: Numeric::N348, name: "Forint", units: 2, symbol: "Ft", countries: "HU" },
    Currency { code: Code::KGS, numeric: Numeric::N417, name: "Som", units: 2, symbol: "лв", countries: "KG" },
    Currency { code: Code::UYI, numeric: Numeric::N940, name: "Uruguay Peso en Unidades Indexadas (UI)", units: 0, symbol: "", countries: "UY" },
    Currency { code: Code::VES, numeric: Numeric::N928, name: "Bolívar Soberano", units: 2, symbol: "", countries: "VE" },
    Currency { code: Code::UYW, numeric: Numeric::N927, name: "Unidad Previsional", units: 4, symbol: "", countries: "UY" },
    Currency { code: Code::COP, numeric: Numeric::N170, name: "Colombian Peso", units: 2, symbol: "$", countries: "CO" },
    Currency { code: Code::XBC, numeric: Numeric::N957, name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", units: 0, symbol: "", countries: "" },
    Currency { code: Code::ANG, numeric: Numeric::N532, name: "Netherlands Antillean Guilder", units: 2, symbol: "ƒ", countries: ",SX" },
    Currency { code: Code::EGP, numeric: Numeric::N818, name: "Egyptian Pound", units: 2, symbol: "£", countries: "EG" },
    Currency { code: Code::KES, numeric: Numeric::N404, name: "Kenyan Shilling", units: 2, symbol: "", countries: "KE" },
    Currency { code: Code::TJS, numeric: Numeric::N972, name: "Somoni", units: 2, symbol: "", countries: "TJ" },
    Currency { code: Code::MXN, numeric: Numeric::N484, name: "Mexican Peso", units: 2, symbol: "$", countries: "MX" },
    Currency { code: Code::CUP, numeric: Numeric::N192, name: "Cuban Peso", units: 2, symbol: "₱", countries: "CU" },
    Currency { code: Code::GHS, numeric: Numeric::N936, name: "Ghana Cedi", units: 2, symbol: "¢", countries: "GH" },
    Currency { code: Code::RWF, numeric: Numeric::N646, name: "Rwanda Franc", units: 0, symbol: "", countries: "RW" },
    Currency { code: Code::RSD, numeric: Numeric::N941, name: "Serbian Dinar", units: 2, symbol: "Дин.", countries: "RS" },
    Currency { code: Code::XDR, numeric: Numeric::N960, name: "SDR (Special Drawing Right)", units: 0, symbol: "", countries: "" },
    Currency { code: Code::SBD, numeric: Numeric::N090, name: "Solomon Islands Dollar", units: 2, symbol: "$", countries: "SB" },
    Currency { code: Code::SOS, numeric: Numeric::N706, name: "Somali Shilling", units: 2, symbol: "S", countries: "SO" },
    Currency { code: Code::XUA, numeric: Numeric::N965, name: "ADB Unit of Account", units: 0, symbol: "", countries: "" },
    Currency { code: Code::SYP, numeric: Numeric::N760, name: "Syrian Pound", units: 2, symbol: "£", countries: "" },
    Currency { code: Code::ZMW, numeric: Numeric::N967, name: "Zambian Kwacha", units: 2, symbol: "", countries: "ZM" },
    Currency { code: Code::MUR, numeric: Numeric::N480, name: "Mauritius Rupee", units: 2, symbol: "₨", countries: "MU" },
    Currency { code: Code::None, numeric: Numeric::None, name: "No universal currency", units: 0, symbol: "", countries: "AQ,PS,GS" },
    Currency { code: Code::MNT, numeric: Numeric::N496, name: "Tugrik", units: 2, symbol: "₮", countries: "MN" },
    Currency { code: Code::SDG, numeric: Numeric::N938, name: "Sudanese Pound", units: 2, symbol: "", countries: "SD" },
    Currency { code: Code::PHP, numeric: Numeric::N608, name: "Philippine Peso", units: 2, symbol: "₱", countries: "PH" },
    Currency { code: Code::MYR, numeric: Numeric::N458, name: "Malaysian Ringgit", units: 2, symbol: "RM", countries: "MY" },
    Currency { code: Code::LBP, numeric: Numeric::N422, name: "Lebanese Pound", units: 2, symbol: "£", countries: "LB" },
    Currency { code: Code::GBP, numeric: Numeric::N826, name: "Pound Sterling", units: 2, symbol: "£", countries: "GG,IM,JE,GB" },
    Currency { code: Code::AOA, numeric: Numeric::N973, name: "Kwanza", units: 2, symbol: "", countries: "AO" },
    Currency { code: Code::BWP, numeric: Numeric::N072, name: "Pula", units: 2, symbol: "P", countries: "BW" },
    Currency { code: Code::DJF, numeric: Numeric::N262, name: "Djibouti Franc", units: 0, symbol: "", countries: "DJ" },
    Currency { code: Code::CLF, numeric: Numeric::N990, name: "Unidad de Fomento", units: 4, symbol: "", countries: "CL" },
    Currency { code: Code::GIP, numeric: Numeric::N292, name: "Gibraltar Pound", units: 2, symbol: "£", countries: "GI" },
    Currency { code: Code::AZN, numeric: Numeric::N944, name: "Azerbaijan Manat", units: 2, symbol: "₼", countries: "AZ" },
    Currency { code: Code::JPY, numeric: Numeric::N392, name: "Yen", units: 0, symbol: "¥", countries: "JP" },
    Currency { code: Code::RON, numeric: Numeric::N946, name: "Romanian Leu", units: 2, symbol: "lei", countries: "RO" },
    Currency { code: Code::SSP, numeric: Numeric::N728, name: "South Sudanese Pound", units: 2, symbol: "", countries: "SS" },
    Currency { code: Code::THB, numeric: Numeric::N764, name: "Baht", units: 2, symbol: "฿", countries: "TH" },
    Currency { code: Code::UYU, numeric: Numeric::N858, name: "Peso Uruguayo", units: 2, symbol: "$U", countries: "UY" },
    Currency { code: Code::SGD, numeric: Numeric::N702, name: "Singapore Dollar", units: 2, symbol: "$", countries: "SG" },
    Currency { code: Code::SAR, numeric: Numeric::N682, name: "Saudi Riyal", units: 2, symbol: "﷼", countries: "SA" },
    Currency { code: Code::MRU, numeric: Numeric::N929, name: "Ouguiya", units: 2, symbol: "", countries: "MR" },
    Currency { code: Code::MGA, numeric: Numeric::N969, name: "Malagasy Ariary", units: 2, symbol: "", countries: "MG" },
    Currency { code: Code::JMD, numeric: Numeric::N388, name: "Jamaican Dollar", units: 2, symbol: "J$", countries: "JM" },
    Currency { code: Code::TTD, numeric: Numeric::N780, name: "Trinidad and Tobago Dollar", units: 2, symbol: "TT$", countries: "TT" },
    Currency { code: Code::LRD, numeric: Numeric::N430, name: "Liberian Dollar", units: 2, symbol: "$", countries: "LR" },
    Currency { code: Code::HKD, numeric: Numeric::N344, name: "Hong Kong Dollar", units: 2, symbol: "$", countries: "HK" },
    Currency { code: Code::KPW, numeric: Numeric::N408, name: "North Korean Won", units: 2, symbol: "₩", countries: "" },
    Currency { code: Code::XXX, numeric: Numeric::N999, name: "The codes assigned for transactions where no currency is involved", units: 0, symbol: "", countries: "" },
    Currency { code: Code::DZD, numeric: Numeric::N012, name: "Algerian Dinar", units: 2, symbol: "", countries: "DZ" },
    Currency { code: Code::BDT, numeric: Numeric::N050, name: "Taka", units: 2, symbol: "", countries: "BD" },
    Currency { code: Code::XOF, numeric: Numeric::N952, name: "CFA Franc BCEAO", units: 0, symbol: "", countries: "BJ,BF,GW,ML,NE,SN,TG" },
    Currency { code: Code::XCD, numeric: Numeric::N951, name: "East Caribbean Dollar", units: 2, symbol: "$", countries: "AI,AG,DM,GD,MS,KN,LC,VC" },
    Currency { code: Code::INR, numeric: Numeric::N356, name: "Indian Rupee", units: 2, symbol: "", countries: "BT,IN" },
    Currency { code: Code::CVE, numeric: Numeric::N132, name: "Cabo Verde Escudo", units: 2, symbol: "", countries: "CV" },
    Currency { code: Code::OMR, numeric: Numeric::N512, name: "Rial Omani", units: 3, symbol: "﷼", countries: "OM" },
    Currency { code: Code::PLN, numeric: Numeric::N985, name: "Zloty", units: 2, symbol: "zł", countries: "PL" },
    Currency { code: Code::SVC, numeric: Numeric::N222, name: "El Salvador Colon", units: 2, symbol: "$", countries: "SV" },
    Currency { code: Code::KRW, numeric: Numeric::N410, name: "Won", units: 0, symbol: "₩", countries: "KR" },
    Currency { code: Code::BBD, numeric: Numeric::N052, name: "Barbados Dollar", units: 2, symbol: "$", countries: "BB" },
    Currency { code: Code::MWK, numeric: Numeric::N454, name: "Malawi Kwacha", units: 2, symbol: "", countries: "MW" },
    Currency { code: Code::RUB, numeric: Numeric::N643, name: "Russian Ruble", units: 2, symbol: "₽", countries: "RU" },
    Currency { code: Code::SHP, numeric: Numeric::N654, name: "Saint Helena Pound", units: 2, symbol: "£", countries: "SH" },
    Currency { code: Code::WST, numeric: Numeric::N882, name: "Tala", units: 2, symbol: "", countries: "WS" },
    Currency { code: Code::DOP, numeric: Numeric::N214, name: "Dominican Peso", units: 2, symbol: "RD$", countries: "DO" },
    Currency { code: Code::BAM, numeric: Numeric::N977, name: "Convertible Mark", units: 2, symbol: "KM", countries: "BA" },
    Currency { code: Code::NOK, numeric: Numeric::N578, name: "Norwegian Krone", units: 2, symbol: "kr", countries: "BV,NO,SJ" },
    Currency { code: Code::GTQ, numeric: Numeric::N320, name: "Quetzal", units: 2, symbol: "Q", countries: "GT" },
    Currency { code: Code::MZN, numeric: Numeric::N943, name: "Mozambique Metical", units: 2, symbol: "MT", countries: "MZ" },
    Currency { code: Code::HTG, numeric: Numeric::N332, name: "Gourde", units: 2, symbol: "", countries: "HT" },
    Currency { code: Code::SRD, numeric: Numeric::N968, name: "Surinam Dollar", units: 2, symbol: "$", countries: "SR" },
    Currency { code: Code::UAH, numeric: Numeric::N980, name: "Hryvnia", units: 2, symbol: "₴", countries: "UA" },
    Currency { code: Code::XTS, numeric: Numeric::N963, name: "Codes specifically reserved for testing purposes", units: 0, symbol: "", countries: "" },
    Currency { code: Code::XPT, numeric: Numeric::N962, name: "Platinum", units: 0, symbol: "", countries: "" },
    Currency { code: Code::PAB, numeric: Numeric::N590, name: "Balboa", units: 2, symbol: "B/.", countries: "PA" },
    Currency { code: Code::ALL, numeric: Numeric::N008, name: "Lek", units: 2, symbol: "Lek", countries: "AL" },
    Currency { code: Code::UGX, numeric: Numeric::N800, name: "Uganda Shilling", units: 0, symbol: "", countries: "UG" },
    Currency { code: Code::KZT, numeric: Numeric::N398, name: "Tenge", units: 2, symbol: "лв", countries: "KZ" },
    Currency { code: Code::ISK, numeric: Numeric::N352, name: "Iceland Krona", units: 0, symbol: "kr", countries: "IS" },
    Currency { code: Code::BIF, numeric: Numeric::N108, name: "Burundi Franc", units: 0, symbol: "", countries: "BI" },
    Currency { code: Code::PYG, numeric: Numeric::N600, name: "Guarani", units: 0, symbol: "Gs", countries: "PY" },
    Currency { code: Code::AED, numeric: Numeric::N784, name: "UAE Dirham", units: 2, symbol: "", countries: "AE" },
    Currency { code: Code::COU, numeric: Numeric::N970, name: "Unidad de Valor Real", units: 2, symbol: "", countries: "CO" },
    Currency { code: Code::XAG, numeric: Numeric::N961, name: "Silver", units: 0, symbol: "", countries: "" },
    Currency { code: Code::SZL, numeric: Numeric::N748, name: "Lilangeni", units: 2, symbol: "", countries: "SZ" },
    Currency { code: Code::XBB, numeric: Numeric::N956, name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", units: 0, symbol: "", countries: "" },
    Currency { code: Code::MOP, numeric: Numeric::N446, name: "Pataca", units: 2, symbol: "", countries: "MO" },
    Currency { code: Code::GYD, numeric: Numeric::N328, name: "Guyana Dollar", units: 2, symbol: "$", countries: "GY" },
    Currency { code: Code::CHE, numeric: Numeric::N947, name: "WIR Euro", units: 2, symbol: "", countries: "CH" },
    Currency { code: Code::FKP, numeric: Numeric::N238, name: "Falkland Islands Pound", units: 2, symbol: "£", countries: "FK" },
    Currency { code: Code::PKR, numeric: Numeric::N586, name: "Pakistan Rupee", units: 2, symbol: "₨", countries: "PK" },
    Currency { code: Code::HRK, numeric: Numeric::N191, name: "Kuna", units: 2, symbol: "kn", countries: "HR" },
    Currency { code: Code::XPF, numeric: Numeric::N953, name: "CFP Franc", units: 0, symbol: "", countries: "PF,NC,WF" },
    Currency { code: Code::YER, numeric: Numeric::N886, name: "Yemeni Rial", units: 2, symbol: "﷼", countries: "YE" },
    Currency { code: Code::KMF, numeric: Numeric::N174, name: "Comorian Franc", units: 0, symbol: "", countries: "KM" },
    Currency { code: Code::SEK, numeric: Numeric::N752, name: "Swedish Krona", units: 2, symbol: "kr", countries: "SE" },
    Currency { code: Code::BZD, numeric: Numeric::N084, name: "Belize Dollar", units: 2, symbol: "BZ$", countries: "BZ" },
    Currency { code: Code::KWD, numeric: Numeric::N414, name: "Kuwaiti Dinar", units: 3, symbol: "", countries: "KW" },
    Currency { code: Code::LSL, numeric: Numeric::N426, name: "Loti", units: 2, symbol: "", countries: "LS" },
    Currency { code: Code::LYD, numeric: Numeric::N434, name: "Libyan Dinar", units: 3, symbol: "", countries: "LY" },
    Currency { code: Code::CHF, numeric: Numeric::N756, name: "Swiss Franc", units: 2, symbol: "CHF", countries: "LI,CH" },
    Currency { code: Code::BOV, numeric: Numeric::N984, name: "Mvdol", units: 2, symbol: "", countries: "BO" },
    Currency { code: Code::NPR, numeric: Numeric::N524, name: "Nepalese Rupee", units: 2, symbol: "₨", countries: "NP" },
    Currency { code: Code::NGN, numeric: Numeric::N566, name: "Naira", units: 2, symbol: "₦", countries: "NG" },
    Currency { code: Code::ETB, numeric: Numeric::N230, name: "Ethiopian Birr", units: 2, symbol: "", countries: "ET" },
    Currency { code: Code::ILS, numeric: Numeric::N376, name: "New Israeli Sheqel", units: 2, symbol: "₪", countries: "IL" },
    Currency { code: Code::TWD, numeric: Numeric::N901, name: "New Taiwan Dollar", units: 2, symbol: "NT$", countries: "TW" },
    Currency { code: Code::TND, numeric: Numeric::N788, name: "Tunisian Dinar", units: 3, symbol: "", countries: "TN" },
    Currency { code: Code::USN, numeric: Numeric::N997, name: "US Dollar (Next day)", units: 2, symbol: "", countries: "US" },
    Currency { code: Code::SLL, numeric: Numeric::N694, name: "Leone", units: 2, symbol: "", countries: "SL" },
    Currency { code: Code::VND, numeric: Numeric::N704, name: "Dong", units: 0, symbol: "₫", countries: "VN" },
    Currency { code: Code::HNL, numeric: Numeric::N340, name: "Lempira", units: 2, symbol: "L", countries: "HN" },
    Currency { code: Code::XBD, numeric: Numeric::N958, name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", units: 0, symbol: "", countries: "" },
    Currency { code: Code::CZK, numeric: Numeric::N203, name: "Czech Koruna", units: 2, symbol: "Kč", countries: "CZ" },
    Currency { code: Code::QAR, numeric: Numeric::N634, name: "Qatari Rial", units: 2, symbol: "﷼", countries: "QA" },
    Currency { code: Code::AFN, numeric: Numeric::N971, name: "Afghani", units: 2, symbol: "؋", countries: "AF" },
    Currency { code: Code::IQD, numeric: Numeric::N368, name: "Iraqi Dinar", units: 3, symbol: "", countries: "IQ" },
    // DATA END
];
