[package]
name = "riso-3166"
version = "0.1.0"
edition = "2018"

[dependencies]
strum = "0.21"
strum_macros = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# ureq = { version = "2.1", features = ["json", "charset"], optional = true }
grep-regex = { version = "0.1", optional = true }
grep-searcher = { version = "0.1", optional = true }
grep-matcher = { version = "0.1", optional = true }

[dev-dependencies]


[features]
default = []
subdivisions = []
updater = [
    "grep-regex",
    "grep-searcher",
    "grep-matcher",
    #"ureq"
]

[[bin]]
name = "update"
path = "src/bin/update.rs"
required-features = ["updater"]
