on:
  release:
    types:
      - published

name: Build Release artifacts & Sync GitHub Pages

jobs:
  sync-gh-pages:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/
        - uses: Bwen/action-ghp-sync@v1-beta
          with:
            source_dir: riso-site/dist
            build_script: bin/gh-pages-build
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
